name: My Recent Posts
on:
  schedule: # Run workflow automatically
    - cron: '30 4 * * 0' # Sunday run
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@vignesh-thirunavukkarasu"
          max_post_count: 10
          
